# Generated by Django 2.2.6 on 2020-01-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('anuncio_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('area', models.TextField()),
                ('pais', models.CharField(max_length=10)),
                ('provincia', models.CharField(choices=[('a', 'Azuay'), ('bo', 'Bolivar'), ('ca', 'Cañar'), ('car', 'Carchi'), ('ch', 'Chimborazo'), ('co', 'Cotopaxi'), ('eo', 'El Oro'), ('e', 'Esmeraldas'), ('ga', 'Galápagos'), ('gu', 'Guayas'), ('i', 'Imbabura'), ('l', 'Loja'), ('lr', 'Los Ríos'), ('ma', 'Manabí'), ('mo', 'Morona Santiago'), ('n', 'Napo'), ('o', 'Orellana'), ('pa', 'Pastaza'), ('pi', 'Pichincha'), ('se', 'Santa Elena'), ('sdt', 'Santo Domingo de los Tsachilas'), ('s', 'Sucumbíos'), ('t', 'Tungurahua'), ('zc', 'Zamora Chinchipe')], max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('postulacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('salario', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Anuncio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona'),
        ),
    ]
