# Generated by Django 3.1.7 on 2021-02-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='provincia',
            field=models.CharField(choices=[('Azuay', 'Azuay'), ('Bolivar', 'Bolivar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsachilas', 'Santo Domingo de los Tsachilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], max_length=80),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
